[project]
name = "five"
version = "0.0.1"
description = ""
authors = [{ name = "Dominic Branford" }]
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "pyyaml>=6.0.1,<7",
    "sqlalchemy>=2.0.25,<3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
